### ISSUE TITLE
Uncaught Error: Unknown signal: SIGQUIT when closing preview tab

### ISSUE THREAD

**Issue by pke** [VictorBjelkholm/atom-react-preview#10]
[Enter steps to reproduce below:]
1. open the preview
2. close the preview tab

**Atom Version**: 1.7.3
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-react-preview](https://github.com/VictorBjelkholm/atom-react-preview) package, v2.0.0
### Stack Trace

Uncaught Error: Unknown signal: SIGQUIT

```
At internal/child_process.js:360

Error: Unknown signal: SIGQUIT
    at ChildProcess.kill (internal/child_process.js:360:11)
    at AtomReactPreviewView.module.exports.AtomReactPreviewView.destroy (file:///C:/Users/xxx_000/.atom/packages/atom-react-preview/lib/atom-react-preview-view.coffee:49:21)
    at Pane.module.exports.Pane.destroyItem (C:\Users\xxx_000\AppData\Local\atom\app-1.7.3\resources\app.asar\src\pane.js:639:18)
    at atom-tabs.TabBarView.onClick (C:\Users\xxx_000\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:658:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-preview, v2.0.0
coffee-navigator, v0.0.18
ctrl-last-tab, v0.3.0
cucumber, v0.5.0
keyboard-localization, v1.4.18
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-eslint, v7.2.2
pretty-json, v1.4.0
react, v0.15.0

# Dev
No dev packages
```

**Comment by Thargarius** [comment]
same problem when I try to open any page :/

1. open the preview

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Windows 10 64 bits Entreprise LTSB build 1607 v.14393.1066
**Thrown From**: [atom-react-preview](https://github.com/VictorBjelkholm/atom-react-preview) package 2.0.0


### Stack Trace

Uncaught Error: Unknown signal: SIGQUIT

```
At internal/child_process.js:375

Error: Unknown signal: SIGQUIT
    at ChildProcess.kill (internal/child_process.js:375:11)
    at AtomReactPreviewView.module.exports.AtomReactPreviewView.destroy (/packages/atom-react-preview/lib/atom-react-preview-view.coffee:49:21)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:660:18)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.18 
atom-clock 0.1.6 
atom-csscomb 2.0.4 
atom-cursor-indent 0.1.1 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-pair 2.0.10 
atom-react-preview 2.0.0 
autoclose-html 0.23.0 
autocomplete-clang 0.10.1 
browser-plus 0.0.87 
build 0.67.0 
busy 0.7.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.3 
git-plus 7.4.0 
glowing-cursor 0.1.2 
intentions 1.1.2 
language-babel 2.57.3 
language-ini 1.19.0 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.1 
platformio-ide-terminal 2.5.0 
pp 0.0.1 
preview 0.17.0 
text-manipulation 0.6.0 
tool-bar 1.1.0 
translator 0.3.0 
```
Disabled packages :
> preview 0.17.0 
> browser-plus 0.0.87 
> pp 0.0.1 
> atom-pair 2.0.10
