### ISSUE TITLE
Uncaught TypeError: Cannot read property 'kill' of null

### ISSUE THREAD

**Issue by 109171650** [VictorBjelkholm/atom-react-preview#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: "Fedora release
**Thrown From**: [atom-react-preview](https://github.com/VictorBjelkholm/atom-react-preview) package 2.0.0
**User**: root

### Stack Trace

Uncaught TypeError: Cannot read property 'kill' of null

```
At /root/.atom/packages/atom-react-preview/lib/atom-react-preview-view.coffee:49

TypeError: Cannot read property 'kill' of null
    at AtomReactPreviewView.module.exports.AtomReactPreviewView.destroy (/packages/atom-react-preview/lib/atom-react-preview-view.coffee:49:20)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:660:18)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:687:19)
```

### Commands

```
     -1:02.9.0 terminal-plus:toggle (input.hidden-input)
  2x -0:52.5.0 pane:reopen-closed-item (textarea.)
     -0:38.1.0 editor:consolidate-selections (input.hidden-input)
     -0:38.1.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-react-preview 2.0.0 
atomic-chrome 0.3.0 
autocomplete-paths 1.0.5 
autoprefixer 3.6.1 
color-picker 2.2.5 
dash 1.7.1 
emmet 2.4.3 
markdown-preview-enhanced 0.12.1 
markdown-scroll-sync 2.1.2 
pretty-json 1.6.3 
react-snippets 0.7.2 
rename-tabs 0.2.0 
terminal-plus 0.14.5 
vim-mode-plus 0.91.0 
```

**Comment by 109171650** [comment]
Uncaught TypeError: Cannot read property 'kill' of null
