### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ayukacha** [VictorBjelkholm/atom-react-preview#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-react-preview](https://github.com/VictorBjelkholm/atom-react-preview) package, v1.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'type' of undefined

```
At /Users/GuyZa/.atom/packages/atom-react-preview/lib/renderer.js:94

TypeError: Cannot read property 'type' of undefined
    at Renderer.render (/Users/GuyZa/.atom/packages/atom-react-preview/lib/renderer.js:94:60)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/GuyZa/.atom/packages/atom-react-preview/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/GuyZa/.atom/packages/atom-react-preview/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/GuyZa/.atom/packages/atom-react-preview/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at /Users/GuyZa/.atom/packages/atom-react-preview/node_modules/react/lib/ReactServerRendering.js:42:38
    at ReactServerRenderingTransaction.Mixin.perform (/Users/GuyZa/.atom/packages/atom-react-preview/node_modules/react/lib/Transaction.js:136:20)
    at Object.renderToString (/Users/GuyZa/.atom/packages/atom-react-preview/node_modules/react/lib/ReactServerRendering.js:40:24)
    at /Users/GuyZa/.atom/packages/atom-react-preview/lib/atom-react-preview-view.coffee:127:36
    at /Users/GuyZa/.atom/packages/atom-react-preview/lib/atom-react-preview-view.coffee:102:7
```
### Commands

```
  3x -0:35.3.0 markdown-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.9.0 atom-react-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-preview, v1.1.4
color-picker, v2.0.14
linter, v1.11.3
minimap, v4.16.2
pigments, v0.19.1
react, v0.12.10
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by victorb** [comment]
Hey, thanks for the creation of this issue!

Could I please ask you for the source of the component you're trying to load? If not, could you provide some other source that reproduces the same issue?

Thanks

**Comment by victorb** [comment]
Hey, just released version 2 of the package, please try this again and if you can reproduce it, please attach the source code and we'll have a look.
